version: '3'
services:
  app:
    image: python
    volumes:
      - .:/app
    working_dir: /app
    build: .
    command: sh -c "python app.py"
    container_name: medapp_Leha
    restart: always
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 512m
